feature: ['feature/*', 'feat/*']
fix: fix/*
test: ['test/*', 'tests/*']
dependencies: ['dependencies/*', 'deps/*', 'dependabot/*']
other: other/*
ignore: ['chore/*', 'build/*', 'refactor/*', 'style/*']