name: 'Push Developement NuGet'
on:
  workflow_dispatch:

jobs:
  init:
    uses: elendil-software/github-actions/.github/workflows/init-workflow.yml@main
  
  gitversion:
    needs: init
    uses: elendil-software/github-actions/.github/workflows/gitversion.yml@main
    with:
      config: './.github/GitVersion.yml'
  
  build:
    needs: gitversion
    uses: elendil-software/github-actions/.github/workflows/dotnet-build.yml@main
  
  nuget-push:
    needs: build
    uses: elendil-software/github-actions/.github/workflows/nuget-push-github.yml@main