name: 'Release'
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/sw_build.yml
    with:
      gitversion-config: './.github/GitVersion-Release.yml'
      push_artifact: true
  
  release:
    needs: [build]
    uses: ./.github/workflows/sw_tag-release.yml
    with:
      git_tag: ${{needs.build.outputs.SemVer}}
      changelog_builder_configuration: './.github/release-changelog-builder-configuration.json'
      
  nuget_push_github:
    name: 'Push .nupkg files to nuget.org'
    runs-on: ubuntu-latest
    steps:
      - name: Push .nupkg files to nuget.org
        run: dotnet nuget push ./Output/IPX800cs/*.nupkg --api-key $API_KEY --source https://api.nuget.org/v3/index.json
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}